theme: jekyll-theme-cayman
title: Pat Niemeyer
description: Thoughts on various things.
github:
  is_project_page: false

social-network-links:
  rss: true
  email: "pat@pat.net"
  github: patniemeyer
  reddit: patniemeyer
  linkedin: patniemeyer
  stackoverflow: 74975/pat-niemeyer
  youtube: patniemeyer

